spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: saifbarakat991@gmail.com
    password: qtruhgoarbzgtihj
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: false
            required: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000