spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/valet}
    username: ${DB_USERNAME:valet}
    password: ${DB_PASSWORD:valet}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
